//! Generated by `just calibrate`; `just calibrate-check` proves it is current.
//! See `calibration` for what these measure.

#[allow(clippy::excessive_precision)] // Written to seven significant digits.
pub(super) const PREAMP_SWEEP: [f32; 11] = [
    4.325_564e-3,
    3.203_555e-3,
    1.548_917e-3,
    6.036_244e-4,
    2.203_460e-4,
    7.924_883e-5,
    2.883_036e-5,
    1.381_109e-5,
    1.126_847e-5,
    1.098_212e-5,
    9.601_968e-6,
];

#[allow(clippy::excessive_precision)] // Written to seven significant digits.
pub(super) const TONE_STACK_SCALE: f32 = 2.412_191e0;

#[allow(clippy::excessive_precision)] // Written to seven significant digits.
pub(super) const POWER_SWEEP: [f32; 11] = [
    6.352_246e-1,
    3.374_166e-1,
    1.864_519e-1,
    1.132_935e-1,
    8.012_906e-2,
    6.589_405e-2,
    6.027_615e-2,
    5.963_952e-2,
    6.023_011e-2,
    6.139_116e-2,
    6.428_187e-2,
];

#[allow(clippy::excessive_precision)] // Written to seven significant digits.
pub(super) const DRIVE_GAIN: [f32; 11] = [
    7.985_045e-1,
    8.737_708e-1,
    1.015_058e0,
    9.920_422e-1,
    9.710_928e-1,
    9.788_806e-1,
    1.134_849e0,
    1.255_718e0,
    1.194_512e0,
    1.193_524e0,
    1.334_387e0,
];

#[allow(clippy::excessive_precision)] // Written to seven significant digits.
pub(super) const GRIT_GAIN: [f32; 11] = [
    1.000_092e0,
    1.000_094e0,
    1.000_092e0,
    1.000_093e0,
    1.000_093e0,
    1.000_000e0,
    1.008_274e0,
    1.098_573e0,
    1.361_050e0,
    1.931_944e0,
    2.965_699e0,
];
