//! Generated by `just calibrate`; `just calibrate-check` proves it is current.
//! See `calibration` for what these measure.

#[allow(clippy::excessive_precision)] // Written to seven significant digits.
pub(super) const PREAMP_SWEEP: [f32; 11] = [
    4.435_604e-3,
    3.285_052e-3,
    1.588_321e-3,
    6.189_987e-4,
    2.256_556e-4,
    8.015_568e-5,
    2.934_485e-5,
    1.388_752e-5,
    1.103_253e-5,
    1.065_729e-5,
    9.383_467e-6,
];

#[allow(clippy::excessive_precision)] // Written to seven significant digits.
pub(super) const TONE_STACK_SCALE: f32 = 2.000_208e0;

#[allow(clippy::excessive_precision)] // Written to seven significant digits.
pub(super) const POWER_SWEEP: [f32; 11] = [
    8.363_393e-1,
    4.349_328e-1,
    2.292_821e-1,
    1.224_547e-1,
    6.833_898e-2,
    4.210_314e-2,
    2.985_109e-2,
    2.406_002e-2,
    2.075_339e-2,
    1.879_771e-2,
    1.804_834e-2,
];

#[allow(clippy::excessive_precision)] // Written to seven significant digits.
pub(super) const DRIVE_GAIN: [f32; 11] = [
    6.172_767e-1,
    7.693_782e-1,
    1.024_354e0,
    9.834_423e-1,
    9.505_921e-1,
    9.807_965e-1,
    1.141_001e0,
    1.170_529e0,
    9.082_302e-1,
    7.089_717e-1,
    6.887_966e-1,
];

#[allow(clippy::excessive_precision)] // Written to seven significant digits.
pub(super) const GRIT_GAIN: [f32; 11] = [
    9.999_399e-1,
    9.999_396e-1,
    9.999_392e-1,
    9.999_399e-1,
    9.999_397e-1,
    9.999_998e-1,
    1.012_927e0,
    1.171_391e0,
    1.614_572e0,
    2.505_271e0,
    4.054_359e0,
];
