//! Generated by `just calibrate`; `just calibrate-check` proves it is current.
//! See `calibration` for what these measure.

#[allow(clippy::excessive_precision)] // Written to seven significant digits.
pub(super) const PREAMP_SWEEP: [f32; 11] = [
    4.480_905e-3,
    3.318_602e-3,
    1.604_671e-3,
    6.273_985e-4,
    2.324_986e-4,
    8.288_800e-5,
    2.941_669e-5,
    1.358_679e-5,
    1.077_736e-5,
    1.036_019e-5,
    9.048_820e-6,
];

#[allow(clippy::excessive_precision)] // Written to seven significant digits.
pub(super) const TONE_STACK_SCALE: f32 = 2.109_704e0;

#[allow(clippy::excessive_precision)] // Written to seven significant digits.
pub(super) const POWER_SWEEP: [f32; 11] = [
    7.454_483e-1,
    3.935_425e-1,
    2.129_753e-1,
    1.237_745e-1,
    8.317_240e-2,
    6.439_231e-2,
    5.564_175e-2,
    5.068_160e-2,
    4.845_799e-2,
    4.955_051e-2,
    4.989_435e-2,
];

#[allow(clippy::excessive_precision)] // Written to seven significant digits.
pub(super) const DRIVE_GAIN: [f32; 11] = [
    7.681_966e-1,
    8.706_641e-1,
    1.042_494e0,
    1.011_573e0,
    9.560_855e-1,
    9.893_261e-1,
    1.318_069e0,
    1.723_930e0,
    1.613_727e0,
    1.467_501e0,
    1.604_967e0,
];

#[allow(clippy::excessive_precision)] // Written to seven significant digits.
pub(super) const GRIT_GAIN: [f32; 11] = [
    1.001_686e0,
    1.001_687e0,
    1.001_686e0,
    1.001_688e0,
    1.001_674e0,
    9.999_999e-1,
    1.023_712e0,
    1.128_495e0,
    1.447_141e0,
    2.037_563e0,
    3.038_307e0,
];
