//! Fits the sections that give the cabinet its reference-rate response at
//! other rates, for `just fit-cabinet` to write as `cabinet_data.rs`.
//!
//! At rates away from the reference, the bilinear low-pass and cabinet shelf
//! match the reference only at their corners: the reference's top end is
//! steeper than any same-order bilinear design there. Six general sections
//! replace them, fitted so that, with every other fixed section as designed at
//! that rate, the cabinet at rest has the reference's magnitude response. Only
//! the magnitude is fitted; the phase differs from the reference's.

use std::f64::consts::PI;

use super::super::filters::Complex;
use super::{
    Biquad, CABINET_SHELF_DB, CABINET_SHELF_HZ, Cabinet, LOW_PASS_HZ, MATCHED_SECTIONS, PEAKS,
    REFERENCE_RATE, Section, Split, bilinear, db_to_gain, design_tangent, low_pass, peak,
};

/// The rates the table covers: the common host rates and the doublings
/// between them.
const RATES: [f32; 10] = [
    32_000., 44_100., 64_000., 88_200., 96_000., 128_000., 176_400., 192_000., 352_800., 384_000.,
];
const POINTS: usize = 400;
const BOTTOM_HZ: f64 = 20.;
const TOP_HZ: f64 = 20_000.;
const TOP_FRACTION: f64 = 0.46;
const MAX_ITERATIONS: usize = 200_000;
/// The fit has converged when this many iterations lower the error by less
/// than `CONVERGED_FRACTION` of it.
const CONVERGENCE_SPAN: usize = 500;
const CONVERGED_FRACTION: f64 = 1e-9;
/// Fitted poles stay this far inside the unit circle, so no section rings
/// for long or rounds onto the circle.
const MAX_POLE_RADIUS: f64 = 0.995;

/// The fit at one rate, with what it achieved.
pub struct Fitted {
    pub sample_rate: f32,
    pub sections: [Section; MATCHED_SECTIONS],
    pub iterations: usize,
    /// Over 20 Hz to 20 kHz, or to 0.46 of the rate below 43.5 kHz.
    pub max_error_db: f64,
    pub max_pole_radius: f64,
}

pub fn fit_all() -> Result<Vec<Fitted>, String> {
    RATES.iter().map(|&rate| fit_rate(rate)).collect()
}

/// The table as Rust source.
pub fn source(fitted: &[Fitted]) -> String {
    let mut text = String::from(
        "//! Generated by `just fit-cabinet`.\n\
         //! See `cabinet::fit` for what these sections are.\n\n\
         #[allow(clippy::excessive_precision, clippy::unreadable_literal)]\n",
    );
    text.push_str(&format!(
        "pub(super) const MATCHED: [(f32, [[f64; 5]; {MATCHED_SECTIONS}]); {}] = [\n",
        fitted.len()
    ));
    for fit in fitted {
        text.push_str(&format!(
            "    (\n        {:?},\n        [\n",
            fit.sample_rate
        ));
        for section in &fit.sections {
            let values: Vec<String> = section.iter().map(|value| format!("{value:?}")).collect();
            text.push_str(&format!("            [{}],\n", values.join(", ")));
        }
        text.push_str("        ],\n    ),\n");
    }
    text.push_str("];\n");
    text
}

fn fit_rate(sample_rate: f32) -> Result<Fitted, String> {
    let reference = Cabinet::designed(REFERENCE_RATE);
    let host = Cabinet::designed(sample_rate);
    let rate = f64::from(sample_rate);
    let top = TOP_HZ.min(TOP_FRACTION * rate);
    let frequencies: Vec<f64> = (0..POINTS)
        .map(|index| BOTTOM_HZ * (top / BOTTOM_HZ).powf(index as f64 / (POINTS - 1) as f64))
        .collect();
    let target: Vec<f64> = frequencies
        .iter()
        .map(|&frequency| {
            log_magnitude(fixed_response(&reference, frequency, true))
                - log_magnitude(fixed_response(&host, frequency, false))
        })
        .collect();
    let initial = starting_sections(sample_rate);
    let (sections, iterations) = fit_magnitude(initial, &frequencies, &target, rate)
        .map_err(|error| format!("{sample_rate} Hz: {error}"))?;
    let max_pole_radius = sections.iter().map(pole_radius).fold(0., f64::max);
    if max_pole_radius > MAX_POLE_RADIUS {
        return Err(format!(
            "{sample_rate} Hz: a fitted pole lies at radius {max_pole_radius}"
        ));
    }
    let max_error_db = frequencies
        .iter()
        .zip(&target)
        .map(|(&frequency, &target)| {
            let z = delay(frequency, rate);
            let fitted: f64 = sections
                .iter()
                .map(|&section| log_magnitude(section_response(section, z)))
                .sum();
            (fitted - target).abs() * 20. / std::f64::consts::LN_10
        })
        .fold(0., f64::max);
    Ok(Fitted {
        sample_rate,
        sections,
        iterations,
        max_error_db,
        max_pole_radius,
    })
}

/// The response of the fixed sections with the controls at rest, with or
/// without the low-pass and the cabinet shelf.
fn fixed_response(cabinet: &Cabinet, frequency: f64, with_replaced: bool) -> Complex {
    let z = delay(frequency, f64::from(cabinet.sample_rate));
    let mut response = chain_response(&cabinet.high_pass, z);
    if with_replaced {
        let (low, _) = split_response(&cabinet.low_pass, z);
        let (shelf_low, shelf_high) = split_response(&cabinet.cabinet_shelf, z);
        response = response * low * (shelf_low + shelf_high * cabinet.cabinet_shelf_gain);
    }
    let resting_dynamic = peak(cabinet.sample_rate, PEAKS[7].0, PEAKS[7].1, PEAKS[7].2);
    for coefficients in cabinet
        .fixed_peaks
        .iter()
        .map(|section| section.coefficients)
        .chain([resting_dynamic, cabinet.fixed_notch.coefficients])
    {
        response = response * section_response(coefficients, z);
    }
    response
}

/// The bilinear designs the fit starts from: the low-pass, and the cabinet
/// shelf factored into minimum-phase sections with the same magnitude.
fn starting_sections(sample_rate: f32) -> [Section; MATCHED_SECTIONS] {
    let low_pass_tangent = design_tangent(sample_rate, LOW_PASS_HZ);
    let shelf = design_tangent(sample_rate, CABINET_SHELF_HZ);
    let ratio = f64::from(db_to_gain(CABINET_SHELF_DB)).powf(-1. / 7.);
    let shelf_section = |damping: f64| {
        let section = bilinear(
            shelf,
            [1., ratio * damping, ratio * ratio],
            [1., damping, 1.],
        );
        scale_numerator(section, 1. / (ratio * ratio))
    };
    [
        bilinear(low_pass_tangent, [0., 0., 1.], [0., 1., 1.]),
        low_pass(sample_rate, LOW_PASS_HZ, 1.),
        scale_numerator(bilinear(shelf, [0., 1., ratio], [0., 1., 1.]), 1. / ratio),
        shelf_section(1.801_937_7),
        shelf_section(1.246_979_6),
        shelf_section(0.445_041_87),
    ]
}

fn scale_numerator(section: Section, scale: f64) -> Section {
    let [b0, b1, b2, a1, a2] = section;
    [b0 * scale, b1 * scale, b2 * scale, a1, a2]
}

/// Levenberg-Marquardt on the log magnitude, run until it converges,
/// accepting only steps that keep every pole inside `MAX_POLE_RADIUS`. Returns the sections and the iterations taken.
fn fit_magnitude<const SECTIONS: usize>(
    mut sections: [Section; SECTIONS],
    frequencies: &[f64],
    target: &[f64],
    sample_rate: f64,
) -> Result<([Section; SECTIONS], usize), String> {
    let delays: Vec<Complex> = frequencies
        .iter()
        .map(|&frequency| delay(frequency, sample_rate))
        .collect();
    let residuals = |sections: &[Section; SECTIONS]| -> Vec<f64> {
        delays
            .iter()
            .zip(target)
            .map(|(&z, &target)| {
                sections
                    .iter()
                    .map(|&section| log_magnitude(section_response(section, z)))
                    .sum::<f64>()
                    - target
            })
            .collect()
    };
    let cost = |residuals: &[f64]| residuals.iter().map(|value| value * value).sum::<f64>();
    let parameters = 5 * SECTIONS;

    let mut current = residuals(&sections);
    let mut current_cost = cost(&current);
    let mut damping = 1e-3;
    let mut span_start_cost = current_cost;
    for iteration in 0..MAX_ITERATIONS {
        if iteration % CONVERGENCE_SPAN == 0 && iteration > 0 {
            if span_start_cost - current_cost < CONVERGED_FRACTION * span_start_cost {
                return Ok((sections, iteration));
            }
            span_start_cost = current_cost;
        }
        let mut normal = vec![0.; parameters * parameters];
        let mut gradient = vec![0.; parameters];
        let mut row = vec![0.; parameters];
        for (&z, &residual) in delays.iter().zip(&current) {
            let z2 = z * z;
            for (index, &[b0, b1, b2, a1, a2]) in sections.iter().enumerate() {
                let numerator = Complex::real(1.) / polynomial(z, [b0, b1, b2]);
                let denominator = Complex::real(1.) / polynomial(z, [1., a1, a2]);
                row[5 * index..5 * index + 5].copy_from_slice(&[
                    numerator.re,
                    (z * numerator).re,
                    (z2 * numerator).re,
                    -(z * denominator).re,
                    -(z2 * denominator).re,
                ]);
            }
            for ((&left, gradient), normal) in row
                .iter()
                .zip(&mut gradient)
                .zip(normal.chunks_exact_mut(parameters))
            {
                *gradient += left * residual;
                for (entry, &right) in normal.iter_mut().zip(&row) {
                    *entry += left * right;
                }
            }
        }
        loop {
            let mut system = normal.clone();
            for i in 0..parameters {
                system[i * parameters + i] *= 1. + damping;
            }
            let step = solve(system, gradient.iter().map(|value| -value).collect());
            let mut candidate = sections;
            for (index, section) in candidate.iter_mut().enumerate() {
                for (value, change) in section.iter_mut().zip(&step[5 * index..]) {
                    *value += change;
                }
            }
            if candidate
                .iter()
                .all(|section| pole_radius(section) <= MAX_POLE_RADIUS)
            {
                let trial = residuals(&candidate);
                let trial_cost = cost(&trial);
                if trial_cost < current_cost {
                    sections = candidate;
                    current = trial;
                    current_cost = trial_cost;
                    damping = (damping / 3.).max(1e-12);
                    break;
                }
            }
            damping *= 4.;
            if damping > 1e12 {
                return Ok((sections, iteration));
            }
        }
    }
    Err(format!("no convergence in {MAX_ITERATIONS} iterations"))
}

/// The largest pole magnitude of `1 + a1 z⁻¹ + a2 z⁻²`; not finite for a
/// non-finite section.
fn pole_radius(&[_, _, _, a1, a2]: &Section) -> f64 {
    let discriminant = a1 * a1 - 4. * a2;
    if discriminant < 0. {
        a2.sqrt()
    } else {
        (a1.abs() + discriminant.sqrt()) / 2.
    }
}

/// Gaussian elimination with partial pivoting; a singular system gives a
/// non-finite step, which the caller's pole check rejects.
fn solve(mut matrix: Vec<f64>, mut vector: Vec<f64>) -> Vec<f64> {
    let size = vector.len();
    for column in 0..size {
        let pivot = (column..size)
            .max_by(|&a, &b| {
                matrix[a * size + column]
                    .abs()
                    .total_cmp(&matrix[b * size + column].abs())
            })
            .unwrap_or(column);
        for k in 0..size {
            matrix.swap(column * size + k, pivot * size + k);
        }
        vector.swap(column, pivot);
        for row in column + 1..size {
            let factor = matrix[row * size + column] / matrix[column * size + column];
            for k in column..size {
                matrix[row * size + k] -= factor * matrix[column * size + k];
            }
            vector[row] -= factor * vector[column];
        }
    }
    for row in (0..size).rev() {
        let sum: f64 = (row + 1..size)
            .map(|k| matrix[row * size + k] * vector[k])
            .sum();
        vector[row] = (vector[row] - sum) / matrix[row * size + row];
    }
    vector
}

fn log_magnitude(response: Complex) -> f64 {
    response.norm_squared().ln() / 2.
}

fn chain_response(sections: &[Biquad], z: Complex) -> Complex {
    sections
        .iter()
        .fold(Complex::real(1.), |response, section| {
            response * section_response(section.coefficients, z)
        })
}

fn split_response<const SECTIONS: usize>(
    split: &Split<SECTIONS>,
    z: Complex,
) -> (Complex, Complex) {
    (
        section_response(split.first_low.coefficients, z) * chain_response(&split.low, z),
        section_response(split.first_high.coefficients, z) * chain_response(&split.high, z),
    )
}

fn section_response([b0, b1, b2, a1, a2]: Section, z: Complex) -> Complex {
    polynomial(z, [b0, b1, b2]) / polynomial(z, [1., a1, a2])
}

/// The unit delay `z⁻¹` at a frequency.
fn delay(frequency: f64, sample_rate: f64) -> Complex {
    Complex::polar(-2. * PI * frequency / sample_rate)
}

fn polynomial(z: Complex, [c0, c1, c2]: [f64; 3]) -> Complex {
    Complex::real(c0) + z * c1 + z * z * c2
}
